#ifndef CONFIG_H
#define CONFIG_H

#define NUM_ALU_UNITS 8
#define NUM_BRANCH_UNITS 8
#define NUM_ADDRESS_UNITS 8
#define NUM_MEMORY_UNITS 8

#define NUM_ALU_RES_STATIONS 128
#define NUM_BRANCH_RES_STATIONS 128
#define NUM_MEMORY_BUFFERS 128

#define INST_QUEUE_SIZE 128

#define REORDER_BUFFER_SIZE 128

#define BTB_SIZE 32
#define BTB_BITS 2

#define ISSUE_WIDTH 8
#define COMMIT_WIDTH 8

#define EXEC_CYCLES_ADD 2
#define EXEC_CYCLES_LUI 2
#define EXEC_CYCLES_AUIPC 2
#define EXEC_CYCLES_SUB 2
#define EXEC_CYCLES_SLL 2
#define EXEC_CYCLES_SLT 2
#define EXEC_CYCLES_SLTU 2
#define EXEC_CYCLES_XOR 2
#define EXEC_CYCLES_SRL 2
#define EXEC_CYCLES_SRA 2
#define EXEC_CYCLES_OR 2
#define EXEC_CYCLES_AND 2

#define EXEC_CYCLES_JAL 2
#define EXEC_CYCLES_JALR 2
#define EXEC_CYCLES_BEQ 2
#define EXEC_CYCLES_BNE 2
#define EXEC_CYCLES_BLT 2
#define EXEC_CYCLES_BLTU 2
#define EXEC_CYCLES_BGE 2
#define EXEC_CYCLES_BGEU 2

#define EXEC_CYCLES_ADDRESS 2

#define MEMORY_CYCLES_LW 2
#define MEMORY_CYCLES_LH 2
#define MEMORY_CYCLES_LHU 2
#define MEMORY_CYCLES_LB 2
#define MEMORY_CYCLES_LBU 2

#endif // CONFIG_H
